import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import MobileHeader from "@/components/navigator/MobileHeader";
import MobileFooter from "@/components/navigator/MobileFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Proper metadata type for Next.js
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Props type for layout
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MobileHeader />

        {/* 🔹 Page Content */}
        <div className="pb-20">{children}</div>

        <MobileFooter />
      </body>
    </html>
  );
}
